# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: notes.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'notes.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bnotes.proto\x12\x08notes.v1\"U\n\x04Note\x12\n\n\x02id\x18\x01 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x02 \x01(\t\x12\x15\n\rcreated_at_ms\x18\x03 \x01(\x03\x12\x15\n\rupdated_at_ms\x18\x04 \x01(\x03\"(\n\x11\x43reateNoteRequest\x12\x13\n\x0b\x64\x65scription\x18\x01 \x01(\t\"\x1c\n\x0eGetNoteRequest\x12\n\n\x02id\x18\x01 \x01(\t\"\x12\n\x10ListNotesRequest\"2\n\x11ListNotesResponse\x12\x1d\n\x05notes\x18\x01 \x03(\x0b\x32\x0e.notes.v1.Note\";\n\x18UpdateDescriptionRequest\x12\n\n\x02id\x18\x01 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x02 \x01(\t\"\x1f\n\x11\x44\x65leteNoteRequest\x12\n\n\x02id\x18\x01 \x01(\t\"\x07\n\x05\x45mpty2\xc9\x02\n\x0cNotesService\x12\x39\n\nCreateNote\x12\x1b.notes.v1.CreateNoteRequest\x1a\x0e.notes.v1.Note\x12\x33\n\x07GetNote\x12\x18.notes.v1.GetNoteRequest\x1a\x0e.notes.v1.Note\x12\x44\n\tListNotes\x12\x1a.notes.v1.ListNotesRequest\x1a\x1b.notes.v1.ListNotesResponse\x12G\n\x11UpdateDescription\x12\".notes.v1.UpdateDescriptionRequest\x1a\x0e.notes.v1.Note\x12:\n\nDeleteNote\x12\x1b.notes.v1.DeleteNoteRequest\x1a\x0f.notes.v1.Emptyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'notes_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_NOTE']._serialized_start=25
  _globals['_NOTE']._serialized_end=110
  _globals['_CREATENOTEREQUEST']._serialized_start=112
  _globals['_CREATENOTEREQUEST']._serialized_end=152
  _globals['_GETNOTEREQUEST']._serialized_start=154
  _globals['_GETNOTEREQUEST']._serialized_end=182
  _globals['_LISTNOTESREQUEST']._serialized_start=184
  _globals['_LISTNOTESREQUEST']._serialized_end=202
  _globals['_LISTNOTESRESPONSE']._serialized_start=204
  _globals['_LISTNOTESRESPONSE']._serialized_end=254
  _globals['_UPDATEDESCRIPTIONREQUEST']._serialized_start=256
  _globals['_UPDATEDESCRIPTIONREQUEST']._serialized_end=315
  _globals['_DELETENOTEREQUEST']._serialized_start=317
  _globals['_DELETENOTEREQUEST']._serialized_end=348
  _globals['_EMPTY']._serialized_start=350
  _globals['_EMPTY']._serialized_end=357
  _globals['_NOTESSERVICE']._serialized_start=360
  _globals['_NOTESSERVICE']._serialized_end=689
# @@protoc_insertion_point(module_scope)
